"use strict";
const $=id=>document.getElementById(id);
const els={app:$('app'),home:$('homeScreen'),quiz:$('quizScreen'),result:$('resultScreen'),error:$('errorScreen'),errorMessage:$('errorMessage'),start:$('startButton'),progress:$('progressText'),category:$('categoryText'),timer:$('timerNumber'),timerRing:$('timerRing'),question:$('questionText'),answers:$('answerList'),feedback:$('feedback'),feedbackTitle:$('feedbackTitle'),feedbackFact:$('feedbackFact'),feedbackSource:$('feedbackSource'),deepCutBadge:$('deepCutBadge'),score:$('scoreText'),classification:$('classificationText'),resultMessage:$('resultMessage'),correct:$('correctStat'),incorrect:$('incorrectStat'),unanswered:$('unansweredStat'),average:$('averageStat'),discoverTitle:$('discoverTitle'),platformLinks:$('platformLinks'),replay:$('replayButton'),share:$('shareButton'),copy:$('copyButton'),shareStatus:$('shareStatus'),shareDialog:$('shareDialog'),shareDialogClose:$('shareDialogClose'),homeBandName:$('homeBandName'),brandHeader:$('brandHeader'),brandHeaderName:$('brandHeaderName'),homeBranding:$('homeBranding'),resultArtwork:$('resultArtwork'),pageDescription:$('pageDescription'),coverCopyright:$('coverCopyright')};
const VERSION='20260714-analytics-v1';
let platform,editionEntry,config,questionBank=[],freshQuestionBank=null,questions=[],index=0,answers=[],locked=false,timerInterval=null,timerDeadline=0,advanceTimeout=null,muted=readMutePreference(),beepedSeconds=new Set(),runStartedAt=0,runCompleted=false;
let ding=null,beep=null,activeSound=null,audioContext=null,activeBufferSource=null;
const audioBuffers=new Map();
const audioCueLog=[];
let analytics={track(){return null},setRun(){return ''},clearRun(){}};

init();
async function init(){try{platform=await fetchJson(`platform.json?v=${VERSION}`);const requested=new URLSearchParams(location.search).get('edition')||platform.defaultEdition;editionEntry=platform.editions.find(edition=>edition.slug===requested&&edition.active);if(!editionEntry)throw new Error(`Unknown edition: ${requested}`);config=await fetchJson(`${editionEntry.config}?v=${VERSION}`);questionBank=await fetchJson(`${config.questionFile}?v=${VERSION}`);validateRuntimeContent();freshQuestionBank=new DeepCutsEngine.FreshQuestionBank(questionBank,config.questionMix);analytics=new DeepCutsAnalytics.Tracker({platformConfig:platform,editionEntry,editionConfig:config});applyConfig();createAudio();syncMuteControls();analytics.track('quiz_page_viewed',{page_location:location.origin+location.pathname},{onceKey:`page:${editionEntry.slug}`});els.start.disabled=false}catch(error){console.error(error);showError('The challenge content could not be loaded. Please refresh and try again.')}}
async function fetchJson(url){const response=await fetch(url,{cache:'no-store'});if(!response.ok)throw new Error(`${url} returned ${response.status}`);return response.json()}
function validateRuntimeContent(){const active=questionBank.filter(q=>q.active);if(active.length<config.numberOfQuestions)throw new Error('Not enough active questions');for(const q of active){const deepCutsFieldsValid=config.mode!=='deepCuts'||(q.explanation&&q.sourceName&&q.sourceURL);if(!q.id||!q.question||!Array.isArray(q.options)||q.options.length!==4||!q.options.includes(q.correctAnswer)||!deepCutsFieldsValid)throw new Error(`Invalid question ${q.id||'unknown'}`)}}
function applyConfig(){const accessibleName=`${config.bandName} Fan Challenge`;document.title=`${config.brandName} – ${config.editionTitle}`;els.homeBandName.textContent=config.bandName;els.brandHeaderName.textContent=config.bandName;els.brandHeader.setAttribute('aria-label',accessibleName);els.homeBranding.setAttribute('aria-label',accessibleName);els.resultArtwork.setAttribute('aria-label',`Aggits for the ${config.bandName} fan challenge`);els.pageDescription.content=config.description;els.coverCopyright.textContent=config.social?.copyright||'copyright Clearlight Creative';els.discoverTitle.textContent=`Discover ${config.bandName}`;els.deepCutBadge.hidden=config.mode!=='deepCuts';document.documentElement.style.setProperty('--accent',config.theme.accent);document.documentElement.style.setProperty('--accent2',config.theme.accentSecondary);document.documentElement.style.setProperty('--brand-art',`url("${config.brandArtwork}")`);buildPlatformLinks()}
function createAudio(){ding=new Audio(`${config.dingSound}?v=${VERSION}`);beep=config.beepSound?new Audio(`${config.beepSound}?v=${VERSION}`):null;for(const sound of[ding,beep].filter(Boolean)){sound.preload='auto';sound.playsInline=true;sound.addEventListener('ended',()=>{if(activeSound===sound)activeSound=null});sound.load()}prepareWebAudio()}
async function prepareWebAudio(){const AudioContextClass=window.AudioContext||window.webkitAudioContext;if(!AudioContextClass)return;try{audioContext=new AudioContextClass();for(const[cue,url]of[['ding',config.dingSound],['beep',config.beepSound]].filter(([,url])=>url)){const response=await fetch(`${url}?v=${VERSION}`);if(!response.ok)continue;audioBuffers.set(cue,await audioContext.decodeAudioData(await response.arrayBuffer()))}}catch{audioContext=null;audioBuffers.clear()}}
function stopSound(sound){if(!sound)return;try{sound.pause();sound.currentTime=0}catch{}}
function stopBufferSource(){if(!activeBufferSource)return;try{activeBufferSource.stop()}catch{}activeBufferSource=null}
function unlockAudio(){if(muted)return;if(audioContext?.state==='suspended')audioContext.resume().catch(()=>{});for(const sound of[ding,beep]){if(!sound)continue;const previousVolume=sound.volume;sound.muted=false;sound.volume=.001;sound.currentTime=0;try{const attempt=sound.play();if(attempt&&attempt.then)attempt.then(()=>{sound.pause();sound.currentTime=0;sound.volume=previousVolume}).catch(()=>{sound.volume=previousVolume})}catch{sound.volume=previousVolume}}}
function playSound(sound,cue){if(!sound||muted)return;stopBufferSource();stopSound(ding);stopSound(beep);activeSound=null;audioCueLog.push({cue,question:index+1,remaining:Number(els.timer.textContent)});document.documentElement.dataset.audioCues=JSON.stringify(audioCueLog);analytics.track('audio_cue',{cue,question:index+1});if(audioContext?.state==='running'&&audioBuffers.has(cue)){const source=audioContext.createBufferSource();source.buffer=audioBuffers.get(cue);source.connect(audioContext.destination);source.addEventListener('ended',()=>{if(activeBufferSource===source)activeBufferSource=null});activeBufferSource=source;source.start();return}activeSound=sound;try{sound.muted=false;sound.volume=1;sound.play()?.catch(()=>{})}catch{}}
function playBeep(){playSound(beep,'beep')}
function playDing(){playSound(ding,'ding')}
function startChallenge(){unlockAudio();startRun('initial')}
function startRun(startType='replay'){clearTimers();questions=freshQuestionBank.nextRound();index=0;answers=[];runStartedAt=Date.now();runCompleted=false;analytics.setRun();analytics.track('quiz_started',{start_type:startType,question_count:questions.length},{dedupeKey:'start',dedupeMs:1000});audioCueLog.length=0;document.documentElement.dataset.audioCues='[]';showScreen(els.quiz);renderQuestion()}
function renderQuestion(){clearTimers();locked=false;beepedSeconds=new Set();els.feedback.hidden=true;els.feedbackSource.hidden=true;els.answers.innerHTML='';const q=questions[index];els.progress.textContent=`Question ${index+1} of ${questions.length}`;els.category.textContent=q.category;els.question.textContent=q.question;els.timer.textContent=String(config.secondsPerQuestion);els.timerRing.classList.remove('urgent');els.timerRing.setAttribute('aria-label',`${config.secondsPerQuestion} seconds remaining`);q.options.forEach((option,optionIndex)=>{const button=document.createElement('button');button.type='button';button.className='answer-button';button.textContent=`${String.fromCharCode(65+optionIndex)}. ${option}`;button.dataset.answer=option;button.addEventListener('click',()=>selectAnswer(option,button));els.answers.append(button)});els.question.focus({preventScroll:true});timerDeadline=performance.now()+config.secondsPerQuestion*1000;timerInterval=setInterval(updateTimer,50)}
function updateTimer(){if(locked)return;const remainingMs=timerDeadline-performance.now();const remaining=Math.max(0,Math.ceil(remainingMs/1000));els.timer.textContent=String(remaining);els.timerRing.setAttribute('aria-label',`${remaining} seconds remaining`);els.timerRing.classList.toggle('urgent',remaining<=3&&remaining>0);if(config.mode==='deepCuts'&&[3,2,1].includes(remaining)&&!beepedSeconds.has(remaining)){beepedSeconds.add(remaining);playBeep()}if(remainingMs<=0)completeAnswer(null,true)}
function selectAnswer(answer,button){if(locked)return;button.classList.add(answer===questions[index].correctAnswer?'correct':'incorrect');completeAnswer(answer,false)}
function completeAnswer(selected,unanswered){if(locked)return;locked=true;clearInterval(timerInterval);timerInterval=null;stopBufferSource();stopSound(beep);activeSound=null;const q=questions[index];const correct=!unanswered&&selected===q.correctAnswer;const responseSeconds=unanswered?config.secondsPerQuestion:Math.min(config.secondsPerQuestion,Math.max(0,(config.secondsPerQuestion*1000-(timerDeadline-performance.now()))/1000));answers.push({id:q.id,selected,correct,unanswered,responseSeconds});for(const button of els.answers.children){button.disabled=true;if(button.dataset.answer===q.correctAnswer)button.classList.add('correct')}
  els.timer.textContent=unanswered?'0':els.timer.textContent;els.timerRing.classList.remove('urgent');els.feedbackTitle.textContent=unanswered?`TIME’S UP — ${q.correctAnswer}`:correct?`CORRECT — ${q.correctAnswer}`:`CORRECT ANSWER — ${q.correctAnswer}`;els.feedbackFact.textContent=q.explanation||q.source||'';if(q.sourceURL){els.feedbackSource.textContent=`Source: ${q.sourceName}`;els.feedbackSource.href=q.sourceURL;els.feedbackSource.hidden=false}else els.feedbackSource.hidden=true;els.feedback.hidden=false;if(config.mode==='deepCuts'){if(unanswered)playDing()}else if(correct)playDing();analytics.track('question_answered',{questionId:q.id,correct,unanswered,responseSeconds});advanceTimeout=setTimeout(()=>{index+=1;if(index>=questions.length)showResults();else renderQuestion()},config.feedbackMilliseconds)}
function showResults(){clearTimers();const stats=DeepCutsEngine.calculateStats(answers,questions.length);const result=DeepCutsEngine.classificationFor(stats.correct,config.classifications,config.bandName);els.score.textContent=`${stats.correct} / ${questions.length}`;els.classification.textContent=result.label;els.resultMessage.textContent=result.message;els.correct.textContent=stats.correct;els.incorrect.textContent=stats.incorrect;els.unanswered.textContent=stats.unanswered;els.average.textContent=`${stats.averageResponseTime.toFixed(1)}s`;els.result.dataset.score=String(stats.correct);els.result.dataset.classification=result.label;showScreen(els.result);if(!runCompleted){runCompleted=true;analytics.track('quiz_completed',{final_score:stats.correct,maximum_score:questions.length,completion_time_seconds:Math.max(0,(Date.now()-runStartedAt)/1000),classification:result.label},{onceKey:`completed:${analytics.runId}`})}}
function showScreen(screen){[els.home,els.quiz,els.result,els.error].forEach(item=>item.hidden=item!==screen);els.app.classList.toggle('home-active',screen===els.home);window.scrollTo({top:0,behavior:'auto'})}
function showError(message){clearTimers();els.errorMessage.textContent=message;showScreen(els.error)}
function clearTimers(){if(timerInterval){clearInterval(timerInterval);timerInterval=null}if(advanceTimeout){clearTimeout(advanceTimeout);advanceTimeout=null}stopBufferSource();stopSound(beep);stopSound(ding);activeSound=null}
function buildPlatformLinks(){const definitions=[['spotify','Open Spotify','spotify'],['bandcamp','Visit Bandcamp','bandcamp'],['youtube','Watch YouTube','youtube'],['instagram','Open Instagram','instagram'],['facebook','Open Facebook','facebook'],['tiktok','Open TikTok','tiktok'],['website','Visit Website','website'],['tickets','Buy Tickets','tickets'],['merchandise','Buy Merch','merchandise'],['mailingList','Join Mailing List','mailing-list']];els.platformLinks.innerHTML='';definitions.forEach(([key,label,className])=>{const url=config.links[key];if(!url)return;const link=document.createElement('a');link.href=url;link.target='_blank';link.rel='noopener noreferrer';link.className=`platform-link ${className}`;link.textContent=label;link.setAttribute('aria-label',`${label} for ${config.bandName} (opens in a new tab)`);link.addEventListener('click',()=>DeepCutsInteractions.trackOutbound(analytics,key,url,Number(els.result.dataset.score)));els.platformLinks.append(link)})}
function resultShareText(){const challengeName=config.mode==='deepCuts'?'Deep Cuts Challenge':'Fan Challenge';return `I scored ${els.result.dataset.score}/${questions.length} in the ${config.bandName} ${challengeName} and earned ${els.result.dataset.classification} status. Can you beat me?`}
async function shareResult(){const finalScore=Number(els.result.dataset.score);analytics.track('share_button_clicked',{final_score:finalScore},{dedupeKey:'main-share',dedupeMs:500});const payload=sharePayload();if(DeepCutsInteractions.supportsNativeShare(navigator,analytics.device)){const status=await DeepCutsInteractions.nativeShare({navigatorObject:navigator,tracker:analytics,payload,actionId:DeepCutsAnalytics.randomId(),finalScore});if(status!=='failed')return}openShareDialog()}
function sharePayload(){return{title:`${config.brandName} – ${config.editionTitle}`,text:resultShareText(),url:config.publicURL||location.href}}
function openShareDialog(){if(typeof els.shareDialog.showModal==='function')els.shareDialog.showModal();else els.shareDialog.setAttribute('open','')}
function closeShareDialog(){if(typeof els.shareDialog.close==='function')els.shareDialog.close();else els.shareDialog.removeAttribute('open')}
function shareVia(method){const payload=sharePayload();const actionId=DeepCutsAnalytics.randomId();const finalScore=Number(els.result.dataset.score);analytics.track('share_method_selected',{share_method:method,share_action_id:actionId,final_score:finalScore},{dedupeKey:`share:${method}`,dedupeMs:500});if(method==='copy_link'){copyQuizLink('share_dialog',actionId);closeShareDialog();return}const url=DeepCutsInteractions.shareMethodUrl(method,payload);closeShareDialog();if(url)window.open(url,'_blank','noopener,noreferrer')}
async function copyQuizLink(trigger='direct_button',actionId=DeepCutsAnalytics.randomId()){const finalScore=Number(els.result.dataset.score);if(trigger==='direct_button')analytics.track('share_method_selected',{share_method:'copy_link',share_action_id:actionId,final_score:finalScore},{dedupeKey:'share:copy_link',dedupeMs:500});const copied=await DeepCutsInteractions.copyLink({clipboard:navigator.clipboard,tracker:analytics,text:config.publicURL||location.href,trigger,actionId,finalScore});els.shareStatus.textContent=copied?'Quiz link copied.':'Copy was blocked. Please copy the address from your browser.'}
function readMutePreference(){try{return localStorage.getItem('fanChallengeMuted')==='true'}catch{return false}}
function setMuted(value){muted=value;if(muted){stopBufferSource();stopSound(beep);stopSound(ding);activeSound=null}try{localStorage.setItem('fanChallengeMuted',String(value))}catch{}syncMuteControls();analytics.track('sound_changed',{muted})}
function syncMuteControls(){document.querySelectorAll('.mute-button').forEach(button=>{button.setAttribute('aria-pressed',String(muted));button.setAttribute('aria-label',muted?'Turn sound on':'Mute sound');button.textContent=button.id==='muteButtonHome'?`Sound: ${muted?'Off':'On'}`:(muted?'×':'♪')})}
function toggleMute(){setMuted(!muted)}
document.addEventListener('visibilitychange',()=>{if(document.hidden&&timerInterval&&!locked){clearTimers();els.timer.textContent=String(config.secondsPerQuestion);els.timerRing.classList.remove('urgent')}else if(!document.hidden&&!els.quiz.hidden&&!locked)renderQuestion()});
window.addEventListener('beforeunload',clearTimers);
els.start.addEventListener('click',startChallenge);els.replay.addEventListener('click',()=>{unlockAudio();startRun('replay')});els.share.addEventListener('click',shareResult);els.copy.addEventListener('click',()=>copyQuizLink());els.shareDialogClose.addEventListener('click',closeShareDialog);els.shareDialog.addEventListener('click',event=>{if(event.target===els.shareDialog)closeShareDialog()});document.querySelectorAll('[data-share-method]').forEach(button=>button.addEventListener('click',()=>shareVia(button.dataset.shareMethod)));document.querySelectorAll('.mute-button').forEach(button=>button.addEventListener('click',toggleMute));
window.__bandChallengeTest={startRun,renderQuestion,completeAnswer,showResults,updateTimer,getState:()=>({index,locked,answerCount:answers.length,timerValue:els.timer.textContent,screen:els.home.hidden?(els.quiz.hidden?'result':'quiz'):'home',questions:questions.map(q=>q.id),audioCueLog:[...audioCueLog],beepedSeconds:[...beepedSeconds],activeSound:activeSound===beep?'beep':activeSound===ding?'ding':null})};
