const state={token:"",bootstrap:null,venues:[],archived:[],selected:new Set(),importText:"",importFileName:"",importToken:"",updateVenueIds:[],updateScope:"selected",runId:"",pollTimer:null,returnVenueId:"",currentVenue:null,currentEffective:null,currentQr:null,currentHistory:[],currentAudit:[],venueDirty:false,qrReady:false,toastTimer:null,publisher:null,publicationJob:null,publicationPollTimer:null,publicationBusy:new Set(),pendingPublicationVenueId:""};
const $=selector=>document.querySelector(selector);
const els={
  csv:$("#csv-file"),restoreVenue:$("#restore-venue"),restoreDialog:$("#restore-dialog"),archivedVenueSelect:$("#archived-venue-select"),archivedEmpty:$("#archived-empty"),confirmRestore:$("#confirm-restore"),updateAll:$("#update-all"),exportReport:$("#export-report"),printReport:$("#print-report"),search:$("#search"),health:$("#health-filter"),publication:$("#publication-filter"),video:$("#video-filter"),gig:$("#gig-filter"),venueType:$("#type-filter"),location:$("#location-filter"),updateState:$("#update-filter"),outcome:$("#outcome-filter"),sort:$("#sort"),rows:$("#venue-rows"),selectAll:$("#select-all"),batchBar:$("#batch-bar"),selectedCount:$("#selected-count"),
  runState:$("#run-state"),runEmpty:$("#run-empty"),runProgress:$("#run-progress"),progressFill:$("#progress-fill"),progressTitle:$("#progress-title"),progressOperation:$("#progress-operation"),progressCompleted:$("#progress-completed"),progressSuccess:$("#progress-success"),progressWarning:$("#progress-warning"),progressFailed:$("#progress-failed"),cancelRun:$("#cancel-run"),retryRun:$("#retry-run"),exportRun:$("#export-run"),runResults:$("#run-results"),
  importDialog:$("#import-dialog"),applyImport:$("#apply-import"),importFile:$("#import-file"),importParsed:$("#import-parsed"),importNew:$("#import-new"),importUpdated:$("#import-updated"),importUnchanged:$("#import-unchanged"),importRejected:$("#import-rejected"),importIssues:$("#import-issues"),
  updateDialog:$("#update-dialog"),updateDialogTitle:$("#update-dialog-title"),updateDialogCount:$("#update-dialog-count"),startUpdate:$("#start-update"),operationUrls:$("#operation-urls"),operationGigs:$("#operation-gigs"),operationTicker:$("#operation-ticker"),operationQr:$("#operation-qr"),
  venueDialog:$("#venue-dialog"),venueForm:$("#venue-form"),venueMaster:$("#venue-master-id"),venueName:$("#venue-name"),venueMeta:$("#venue-meta"),venueHealth:$("#venue-health"),venueHealthDetails:$("#venue-health-details"),venuePublishedToggle:$("#venue-published-toggle"),publicationToggleLabel:$("#publication-toggle-label"),publicationToggleDetail:$("#publication-toggle-detail"),venuePublicUrl:$("#venue-public-url"),venueQrUrl:$("#venue-qr-url"),venueLinks:$("#venue-links"),venueTicker:$("#venue-ticker"),venuePinned:$("#venue-pinned"),generatedTicker:$("#generated-ticker"),tickerSource:$("#ticker-source"),venueAbout:$("#venue-about"),effectiveAbout:$("#effective-about"),aboutSource:$("#about-source"),venueNotes:$("#venue-notes"),venueVideo:$("#venue-video"),venueVideoState:$("#venue-video-state"),removeVenueVideo:$("#remove-venue-video"),saveVenue:$("#save-venue"),updateVenue:$("#update-venue"),checkVenue:$("#check-venue"),venuePreview:$("#venue-preview"),refreshVenuePreview:$("#refresh-venue-preview"),venueResult:$("#venue-result"),venueHistory:$("#venue-history"),venueAudit:$("#venue-audit"),qrState:$("#qr-state"),qrCanvas:$("#venue-qr-canvas"),qrSource:$("#venue-qr-source"),qrValidation:$("#qr-validation"),generateQr:$("#generate-qr"),downloadQr:$("#download-qr"),printQr:$("#print-qr"),publicationStatus:$("#publication-status"),publicationProgress:$("#publication-progress"),publicationProgressFill:$("#publication-progress-fill"),publicationLimit:$("#publication-limit"),publicationLinks:$("#publication-links"),toast:$("#toast")
};

init().catch(error=>showError(error.message));

async function init(){
  const studio=await api("/api/studio/bootstrap",null,{method:"GET",token:false});state.token=studio.token;
  bind();await Promise.all([refreshLibrary(),refreshPublisher()]);
}

function bind(){
  els.csv.addEventListener("change",previewCsv);
  els.restoreVenue.addEventListener("click",openRestoreVenue);
  els.confirmRestore.addEventListener("click",restoreSelectedVenue);
  els.applyImport.addEventListener("click",applyCsv);
  let searchTimer;els.search.addEventListener("input",()=>{clearTimeout(searchTimer);searchTimer=setTimeout(refreshLibrary,180)});
  [els.health,els.publication,els.video,els.gig,els.venueType,els.location,els.updateState,els.outcome,els.sort].forEach(control=>control.addEventListener("change",refreshLibrary));
  document.querySelectorAll("[data-health-filter]").forEach(button=>button.addEventListener("click",()=>{els.health.value=button.dataset.healthFilter;refreshLibrary()}));
  els.rows.addEventListener("click",event=>{const open=event.target.closest("[data-open-venue]");if(open)openVenue(open.dataset.openVenue)});
  els.rows.addEventListener("change",event=>{const publication=event.target.closest("[data-publication-toggle]");if(publication){setPublication(publication.dataset.publicationToggle,publication.checked,publication);return}const checkbox=event.target.closest("[data-select-venue]");if(checkbox){checkbox.checked?state.selected.add(checkbox.value):state.selected.delete(checkbox.value);renderBatch()}});
  els.selectAll.addEventListener("change",()=>{for(const venue of state.venues)els.selectAll.checked?state.selected.add(venue.id):state.selected.delete(venue.id);renderVenues();renderBatch()});
  $("#clear-selected").addEventListener("click",()=>{state.selected.clear();renderVenues();renderBatch()});
  $("#update-selected").addEventListener("click",()=>openUpdate([...state.selected],"selected"));
  $("#check-selected").addEventListener("click",()=>openUpdate([...state.selected],"selected",{urls:true,gigs:false,ticker:false,qr:false}));
  els.updateAll.addEventListener("click",()=>openUpdate(state.venues.map(venue=>venue.id),"all"));
  els.startUpdate.addEventListener("click",startUpdate);
  els.cancelRun.addEventListener("click",cancelRun);
  els.retryRun.addEventListener("click",retryRun);
  els.exportRun.addEventListener("click",()=>state.runId&&window.open(`/api/studio/venue-jobs/${state.runId}/export`,"_blank","noopener,noreferrer"));
  els.exportReport.addEventListener("click",()=>window.open(`/api/studio/venue-reports/operations.csv${filterQuery()}`,"_blank","noopener,noreferrer"));
  els.printReport.addEventListener("click",()=>window.open(`/api/studio/venue-reports/print${filterQuery()}`,"_blank","noopener,noreferrer"));
  els.saveVenue.addEventListener("click",saveVenue);
  els.updateVenue.addEventListener("click",()=>runCurrentVenue("update"));
  els.checkVenue.addEventListener("click",()=>runCurrentVenue("urls"));
  els.refreshVenuePreview.addEventListener("click",refreshVenuePreview);
  els.venueVideo.addEventListener("change",uploadVenueVideo);
  els.removeVenueVideo.addEventListener("click",removeVenueVideo);
  els.venuePublishedToggle.addEventListener("change",()=>setPublication(state.currentVenue?.id,els.venuePublishedToggle.checked,els.venuePublishedToggle));
  els.generateQr.addEventListener("click",generateQrArtwork);
  els.downloadQr.addEventListener("click",downloadQrArtwork);
  els.printQr.addEventListener("click",()=>window.print());
  els.venueForm.addEventListener("input",()=>{state.venueDirty=true});
  els.venueDialog.addEventListener("cancel",event=>{if(state.venueDirty&&!confirm("Close without saving your venue changes?"))event.preventDefault()});
  els.venueDialog.addEventListener("close",()=>{state.currentVenue=null;state.venueDirty=false;state.qrReady=false;state.publicationJob=null});
}

async function refreshLibrary(){
  const result=await api(`/api/studio/venues${filterQuery()}`,null,{method:"GET",token:false});state.bootstrap=result.bootstrap;state.venues=result.venues;renderSummary();renderVenues();renderBatch();
}

function filterQuery(){const params=new URLSearchParams();if(els.search.value.trim())params.set("search",els.search.value.trim());if(els.health.value)params.set("health",els.health.value);if(els.publication.value)params.set("publication",els.publication.value);if(els.video.value)params.set("video",els.video.value);if(els.gig.value)params.set("gigFreshness",els.gig.value);if(els.venueType.value)params.set("venueType",els.venueType.value);if(els.location.value)params.set("location",els.location.value);if(els.updateState.value)params.set("updateState",els.updateState.value);if(els.outcome.value)params.set("updateOutcome",els.outcome.value);if(els.sort.value)params.set("sort",els.sort.value);return params.size?`?${params}`:""}
function renderSummary(){const boot=state.bootstrap||{};for(const color of["red","amber","green","grey"])$(`#health-${color}`).textContent=boot.healthCounts?.[color]||0;$("#venue-count").textContent=`${boot.venueCount||0} active venue${boot.venueCount===1?"":"s"}`;$("#last-sync").textContent=boot.archivedVenueCount?`${boot.archivedVenueCount} safely archived · hidden from active view`:boot.lastSyncAt?`Last sync ${formatDateTime(boot.lastSyncAt)} · ${boot.masterFileName}`:"Ready for your first venue";populateSelect(els.venueType,"All venue types",boot.venueTypes||[]);populateSelect(els.location,"All locations",boot.locations||[]);els.updateAll.disabled=!boot.venueCount}
function renderVenues(){
  if(!state.venues.length){els.rows.innerHTML='<tr><td colspan="8" class="empty">Your active library is empty. Press Add Venue to return one preserved venue, or import a new one.</td></tr>';return}
  els.rows.innerHTML=state.venues.map(venue=>`<tr><td><input type="checkbox" data-select-venue value="${escapeHtml(venue.id)}" aria-label="Select ${escapeHtml(venue.venueName)}" ${state.selected.has(venue.id)?"checked":""}></td><td><strong>${escapeHtml(venue.venueName)}</strong><small>${escapeHtml(venue.masterId)} · ${escapeHtml(venue.venueType||"Venue")} · ${escapeHtml(venue.location||venue.suburb||"")}</small></td><td><label class="switch table-switch" title="${venue.publicationState==="published"?"Published":"Unpublished"}"><input type="checkbox" role="switch" data-publication-toggle="${escapeHtml(venue.id)}" aria-label="Publish ${escapeHtml(venue.venueName)}" ${venue.publicationState==="published"?"checked":""} ${state.publicationBusy.has(venue.id)?"disabled":""}><span></span></label></td><td><span class="status-dot ${escapeHtml(venue.health)}">${escapeHtml(venue.health)}</span><small>${escapeHtml(venue.healthReason||"")}</small></td><td>${humanStatus(venue.gigStatus)}</td><td>${venue.videoStatus==="present"?"Custom MP4":"Placeholder"}</td><td>${venue.lastSuccessfulUpdate?formatDateTime(venue.lastSuccessfulUpdate):"Never"}</td><td><button class="open-venue" type="button" data-open-venue="${escapeHtml(venue.id)}">Open</button></td></tr>`).join("");
}
function renderBatch(){els.selectedCount.textContent=state.selected.size;els.batchBar.hidden=state.selected.size===0;els.selectAll.checked=state.venues.length>0&&state.venues.every(venue=>state.selected.has(venue.id));els.selectAll.indeterminate=!els.selectAll.checked&&state.venues.some(venue=>state.selected.has(venue.id))}

async function previewCsv(){
  const file=els.csv.files[0];if(!file)return;if(file.size>10*1024*1024){showError("The selected CSV is larger than the 10 MB local import limit.");return}
  try{state.importText=await file.text();state.importFileName=file.name;const result=await api("/api/studio/venues/import/preview",{fileName:file.name,csvText:state.importText},{method:"POST"});state.importToken=result.previewToken;renderImport(result.preview);els.importDialog.showModal()}catch(error){showError(error.message)}finally{els.csv.value=""}
}
function renderImport(preview){els.importFile.textContent=`${preview.fileName} · checksum ${preview.checksum.slice(0,12)}…`;els.importParsed.textContent=preview.parsedRows;els.importNew.textContent=preview.newCount;els.importUpdated.textContent=preview.updatedCount;els.importUnchanged.textContent=preview.unchangedCount;els.importRejected.textContent=preview.rejectedRows;const issues=[...(preview.errors||[]),...(preview.warnings||[])].slice(0,20);els.importIssues.innerHTML=issues.map(issue=>`<p><strong>Row ${issue.row}${issue.masterId?` · ${escapeHtml(issue.masterId)}`:""}</strong><br>${escapeHtml(issue.message)}</p>`).join("");els.importIssues.hidden=!issues.length;els.applyImport.disabled=preview.acceptedRows===0}
async function applyCsv(){try{els.applyImport.disabled=true;const result=await api("/api/studio/venues/import/apply",{fileName:state.importFileName,csvText:state.importText,previewToken:state.importToken},{method:"POST"});els.importDialog.close();state.bootstrap=result.bootstrap;state.venues=result.venues;renderSummary();renderVenues();showToast(`${result.importRecord.acceptedRows} venues synchronised. ${result.importRecord.newCount} new, ${result.importRecord.updatedCount} updated.`)}catch(error){showError(error.message)}finally{els.applyImport.disabled=false}}

async function openRestoreVenue(){try{const result=await api("/api/studio/venues-archived",null,{method:"GET",token:false});state.archived=result.venues||[];els.archivedVenueSelect.replaceChildren(...state.archived.map(venue=>new Option(`${venue.venueName} · ${venue.masterId}`,venue.id)));els.archivedVenueSelect.hidden=!state.archived.length;els.archivedEmpty.hidden=state.archived.length>0;els.confirmRestore.disabled=!state.archived.length;els.restoreDialog.showModal()}catch(error){showError(error.message)}}
async function restoreSelectedVenue(){const id=els.archivedVenueSelect.value;if(!id)return;try{els.confirmRestore.disabled=true;await api(`/api/studio/venues/${id}/visibility`,{visibility:"active"},{method:"PUT"});els.restoreDialog.close();await refreshLibrary();showToast("Venue added. Its permanent URL, QR and publication state were preserved.")}catch(error){showError(error.message)}finally{els.confirmRestore.disabled=false}}

function openUpdate(ids,scope,preset={urls:true,gigs:true,ticker:true,qr:false}){if(!ids.length)return;state.updateVenueIds=ids;state.updateScope=scope;els.updateDialogTitle.textContent=scope==="all"?"Update all venues":scope==="single"?"Update this venue":"Update selected venues";els.updateDialogCount.textContent=`${ids.length} venue${ids.length===1?"":"s"} will be processed locally while Studio remains open.`;els.operationUrls.checked=preset.urls;els.operationGigs.checked=preset.gigs;els.operationTicker.checked=preset.ticker;els.operationQr.checked=preset.qr;els.updateDialog.showModal()}
async function startUpdate(){try{els.startUpdate.disabled=true;const result=await api("/api/studio/venue-jobs",{scope:state.updateScope,venueIds:state.updateVenueIds,operations:{checkUrls:els.operationUrls.checked,retrieveGigs:els.operationGigs.checked,regenerateTickers:els.operationTicker.checked,regenerateQr:els.operationQr.checked}},{method:"POST"});els.updateDialog.close();watchRun(result.run.id)}catch(error){showError(error.message)}finally{els.startUpdate.disabled=false}}
function watchRun(runId){state.runId=runId;clearTimeout(state.pollTimer);pollRun()}
async function pollRun(){
  if(!state.runId)return;try{const result=await api(`/api/studio/venue-jobs/${state.runId}`,null,{method:"GET",token:false});renderRun(result.run);if(["queued","running"].includes(result.run.status))state.pollTimer=setTimeout(pollRun,600);else{await refreshLibrary();if(state.returnVenueId){const id=state.returnVenueId;state.returnVenueId="";await openVenue(id)}}}catch(error){showError(error.message)}
}
function renderRun(run){
  els.runEmpty.hidden=true;els.runProgress.hidden=false;els.runState.textContent=run.status.toUpperCase();els.runState.className=`run-state ${run.status}`;els.progressFill.style.width=`${run.totalCount?Math.round(run.completedCount/run.totalCount*100):0}%`;els.progressTitle.textContent=run.status==="completed"?"Update complete":run.currentVenueName||"Preparing update";els.progressOperation.textContent=run.currentOperation||"Waiting";els.progressCompleted.textContent=`${run.completedCount} / ${run.totalCount}`;els.progressSuccess.textContent=run.successCount;els.progressWarning.textContent=run.warningCount;els.progressFailed.textContent=run.failureCount;els.cancelRun.hidden=run.status!=="running";els.retryRun.hidden=run.status!=="completed"||run.failureCount===0;els.exportRun.hidden=!run.results.length;els.runResults.innerHTML=(run.results||[]).slice().reverse().map(item=>`<li><strong>${escapeHtml(item.venueName)} · ${escapeHtml(item.status)}</strong>${escapeHtml(item.summary)}</li>`).join("");
}
async function cancelRun(){if(!state.runId)return;try{await api(`/api/studio/venue-jobs/${state.runId}/cancel`,{}, {method:"POST"});showToast("Cancellation requested. Studio will safely finish the current venue, then stop.")}catch(error){showError(error.message)}}
async function retryRun(){if(!state.runId)return;try{const result=await api(`/api/studio/venue-jobs/${state.runId}/retry`,{}, {method:"POST"});watchRun(result.run.id)}catch(error){showError(error.message)}}

async function openVenue(id){
  try{const result=await api(`/api/studio/venues/${id}`,null,{method:"GET",token:false});state.currentVenue=result.venue;state.currentEffective=result.effective;state.currentQr=result.qr;state.currentHistory=result.history||[];state.currentAudit=result.audit||[];state.publicationJob=result.venue.admin?.publication||null;state.venueDirty=false;state.qrReady=false;renderVenueEditor();els.venueDialog.showModal();setTimeout(()=>els.venueName.focus(),30)}catch(error){showError(error.message)}
}
function renderVenueEditor(){
  const venue=state.currentVenue,csv=venue.csv,admin=venue.admin,effective=state.currentEffective;els.venueMaster.textContent=venue.masterId;els.venueName.textContent=csv.venueName;els.venueName.tabIndex=-1;els.venueMeta.textContent=[csv.venueType,csv.location,csv.suburb,csv.state,csv.postcode].filter(Boolean).join(" · ");els.venueHealth.textContent=(venue.health?.overall||"grey").toUpperCase();els.venueHealth.className=`venue-health ${venue.health?.overall||"grey"}`;els.venuePublishedToggle.checked=admin.publicationState==="published";els.venuePublicUrl.value=admin.publicEditionUrl||"";els.venueQrUrl.value=admin.intendedQrUrl||"";els.venueTicker.value=admin.tickerOverride||"";els.venuePinned.value=admin.tickerPinnedNotice||"";els.generatedTicker.textContent=venue.automated?.generatedTicker?.tickerText||effective.tickerText;els.tickerSource.textContent=`Active source: ${sourceLabel(effective.tickerSource)}`;els.venueAbout.value=admin.aboutOverride||"";els.effectiveAbout.textContent=effective.aboutText;els.aboutSource.textContent=`Active source: ${sourceLabel(effective.aboutSource)}`;els.venueNotes.value=admin.notes||"";els.venueVideoState.textContent=admin.customVideo?`${admin.customVideo.fileName} · ${formatBytes(admin.customVideo.sizeBytes)}`:"Custom video not yet added";els.removeVenueVideo.hidden=!admin.customVideo;els.venueResult.textContent=venue.lastUpdateResult?`${venue.lastUpdateResult.status.toUpperCase()} · ${venue.lastUpdateResult.summary} · ${formatDateTime(venue.lastUpdateResult.completedAt)}`:"This venue has not been updated.";renderVenueLinks(csv);renderVenueHistory(venue);renderPublication();els.venuePreview.src=`/api/studio/venues/${venue.id}/preview?revision=${venue.revision}`;els.qrState.textContent=state.currentQr.label;els.generateQr.disabled=!state.currentQr.destination;els.downloadQr.disabled=true;els.printQr.disabled=true;els.qrValidation.textContent="";drawQrPlaceholder();state.venueDirty=false;
}
function renderVenueHistory(venue){const components=venue.health?.components||{};els.venueHealthDetails.innerHTML=Object.entries(components).map(([name,value])=>`<div><strong>${escapeHtml(humanStatus(name))}</strong><span>${escapeHtml(humanStatus(value))}</span></div>`).join("")||"<p>Not checked.</p>";els.venueHistory.innerHTML=state.currentHistory.map(item=>`<li><strong>${escapeHtml(humanStatus(item.status))} · ${formatDateTime(item.completedAt||item.runFinishedAt)}</strong>${escapeHtml(item.summary||"")}</li>`).join("")||"<li>No venue update history yet.</li>";els.venueAudit.innerHTML=state.currentAudit.map(item=>`<li><strong>${escapeHtml(humanStatus(item.type))}</strong>${formatDateTime(item.at||item.createdAt)}</li>`).join("")||"<li>No venue-specific audit entries yet.</li>"}
function renderVenueLinks(csv){const links=[["Website",csv.websiteUrl],["Gigs / What’s On",csv.gigsUrl],["Menu",csv.menuUrl],["Contact",csv.contactUrl],["Instagram",csv.instagramUrl],["Facebook",csv.facebookUrl],["About",csv.aboutUrl]];els.venueLinks.innerHTML=links.filter(([,url])=>url).map(([label,url])=>`<a href="${escapeHtml(url)}" target="_blank" rel="noopener noreferrer"><strong>${escapeHtml(label)}</strong>${escapeHtml(displayUrl(url))}</a>`).join("")}
async function saveVenue({quiet=false}={}){
  if(!state.currentVenue)return false;try{els.saveVenue.disabled=true;const body={expectedRevision:state.currentVenue.revision,admin:{tickerOverride:els.venueTicker.value,tickerPinnedNotice:els.venuePinned.value,aboutOverride:els.venueAbout.value,notes:els.venueNotes.value}};const result=await api(`/api/studio/venues/${state.currentVenue.id}`,body,{method:"PUT"});state.currentVenue=result.venue;state.currentEffective=result.effective;state.currentQr=result.qr;renderVenueEditor();await refreshLibrary();if(!quiet)showToast("Venue changes saved. CSV synchronisation will preserve them.");return true}catch(error){showError(error.message);return false}finally{els.saveVenue.disabled=false}}

async function refreshPublisher(){
  try{const result=await api("/api/studio/venue-publications/capabilities",null,{method:"GET",token:false});state.publisher=result;els.publicationLimit.textContent=`Camtasia canvas/export: 1114 × 1205 px. Public welcome video limit: ${result.maxVideoLabel}.`}catch(error){state.publisher={authentication:{available:false,reason:error.message},maxVideoBytes:24*1024*1024}}
  if(state.currentVenue)renderPublication();
}
async function setPublication(id,published,control){
  if(!id||state.publicationBusy.has(id))return;const previous=!published;let pending=false;state.publicationBusy.add(id);if(control)control.disabled=true;renderVenues();
  try{
    if(state.currentVenue?.id===id&&state.venueDirty&&!(await saveVenue({quiet:true})))throw new Error("Save the venue changes before publishing.");
    const result=await api(`/api/studio/venues/${id}/publication`,{published},{method:"PUT"});
    if(result.pending&&result.job){pending=true;state.pendingPublicationVenueId=id;state.publicationJob=result.job;watchPublication(result.job.id,id);showToast("Publishing started. Studio is validating, deploying and testing the permanent QR.");return}
    if(state.currentVenue?.id===id)await reloadCurrentVenue();await refreshLibrary();showToast(published?"Published. The same permanent URL and QR are active.":"Unpublished. The permanent URL and QR identity have been preserved.");
  }catch(error){if(control)control.checked=previous;showError(error.message)}finally{if(!pending){state.publicationBusy.delete(id);if(control)control.disabled=false}renderVenues();if(state.currentVenue?.id===id)renderPublication()}
}
function watchPublication(jobId,venueId=state.currentVenue?.id||""){clearTimeout(state.publicationPollTimer);state.pendingPublicationVenueId=venueId||state.pendingPublicationVenueId;pollPublication(jobId)}
async function pollPublication(jobId){
  try{const result=await api(`/api/studio/venue-publications/${jobId}`,null,{method:"GET",token:false});state.publicationJob=result.job;if(state.currentVenue)renderPublication();if(["queued","running"].includes(result.job.status)){state.publicationPollTimer=setTimeout(()=>pollPublication(jobId),1800);return}const id=state.pendingPublicationVenueId;state.publicationBusy.delete(id);state.pendingPublicationVenueId="";await reloadCurrentVenue();await refreshLibrary();if(result.job.status==="published")showToast("Venue is live. The permanent QR and delivery email are confirmed.");else showError(result.job.error||"Publication stopped safely.")}catch(error){state.publicationBusy.delete(state.pendingPublicationVenueId);state.pendingPublicationVenueId="";showError(error.message)}
}
async function reloadCurrentVenue(){
  if(!state.currentVenue)return;const result=await api(`/api/studio/venues/${state.currentVenue.id}`,null,{method:"GET",token:false});state.currentVenue=result.venue;state.currentEffective=result.effective;state.currentQr=result.qr;state.currentHistory=result.history||[];state.currentAudit=result.audit||[];state.publicationJob=result.venue.admin?.publication||state.publicationJob;renderVenueEditor();
}
function renderPublication(){
  if(!state.currentVenue)return;const venue=state.currentVenue,job=state.publicationJob||venue.admin?.publication,authentication=state.publisher?.authentication||{available:false,reason:"Publishing connection unavailable"},active=["queued","running"].includes(job?.status),published=venue.admin?.publicationState==="published",issues=publicationIssues(venue,state.publisher?.maxVideoBytes||24*1024*1024);
  els.venuePublishedToggle.checked=published;els.venuePublishedToggle.disabled=active||state.publicationBusy.has(venue.id);els.publicationToggleLabel.textContent=active?"Publishing…":published?"Published":"Unpublished";els.publicationToggleDetail.textContent=published?"Switch off to hide the live page without changing its permanent URL or QR.":venue.admin?.publicEditionUrl?"Switch on to restore the same permanent URL and QR.":"Switch on when the venue is ready for its first publication.";
  const status=active?(job?.stage||"publishing"):published?"published":job?.status==="failed"||job?.status==="interrupted"?job.status:"draft",heading=published?"Live and verified":active?humanStatus(job.stage||"Publishing"):status==="failed"||status==="interrupted"?"Publication stopped safely":"Unpublished";
  const detail=active?(job.message||"Automatic checks are running."):published?(venue.admin.publicEditionUrl||"Live publication confirmed."):status==="failed"||status==="interrupted"?(job.error||job.message):!authentication.available?(authentication.reason||"Publishing is not available on this installation."):venue.admin?.publicEditionUrl?"Permanent identity preserved and ready to restore.":issues.length?issues.join(" "):"Ready for first publication.";
  els.publicationStatus.className=`publication-status ${escapeHtml(status)}`;els.publicationStatus.innerHTML=`<strong>${escapeHtml(heading)}</strong><span>${escapeHtml(detail)}</span>`;
  const progress={queued:4,preparing:8,validating:15,uploading:32,qr:48,publishing:65,delivery:78,verifying:91,delivered:98,published:100,failed:100,interrupted:100}[job?.stage||status]||0;els.publicationProgress.hidden=!active;els.publicationProgressFill.style.width=`${progress}%`;
  const links=[];if(venue.admin?.publicEditionUrl)links.push(["Open permanent venue URL",venue.admin.publicEditionUrl]);if(job?.qrImageUrl)links.push(["Open permanent QR",job.qrImageUrl]);els.publicationLinks.hidden=!links.length;els.publicationLinks.innerHTML=links.map(([label,url])=>`<a href="${escapeHtml(url)}" target="_blank" rel="noopener noreferrer">${escapeHtml(label)} ↗</a>`).join("");
}
function publicationIssues(venue,maxBytes){
  const issues=[],csv=venue.csv||{},video=venue.admin?.customVideo;for(const field of["gigsUrl","menuUrl","contactUrl","instagramUrl","facebookUrl"])if(!isPublicHttps(csv[field]))issues.push("All five verified HTTPS button destinations are required.");
  if(!video)issues.push("Add the local MP4 welcome video.");else if(Number(video.sizeBytes)>maxBytes)issues.push(`Re-export the welcome MP4 below ${Math.floor(maxBytes/1024/1024)} MB for public deployment.`);
  if(!state.currentEffective?.tickerText)issues.push("Ticker text is required.");if(!state.currentEffective?.aboutText)issues.push("About Us copy is required.");return[...new Set(issues)];
}
function isPublicHttps(value){try{const url=new URL(String(value||""));return url.protocol==="https:"&&!url.username&&!url.password&&!url.hostname.match(/^(localhost|127\.|10\.|192\.168\.)/i)}catch{return false}}
async function runCurrentVenue(action){if(!state.currentVenue)return;if(state.venueDirty&&!confirm("Run the update without saving the current edits?"))return;const id=state.currentVenue.id;state.returnVenueId=id;els.venueDialog.close();const result=await api(`/api/studio/venues/${id}/${action}`,{}, {method:"POST"});watchRun(result.run.id)}
function refreshVenuePreview(){if(state.currentVenue)els.venuePreview.src=`/api/studio/venues/${state.currentVenue.id}/preview?refresh=${Date.now()}`}
async function uploadVenueVideo(){const file=els.venueVideo.files[0];if(!file||!state.currentVenue)return;if(file.size>500*1024*1024){showError("The selected MP4 exceeds the 500 MB limit.");return}try{const result=await api(`/api/studio/venues/${state.currentVenue.id}/video`,file,{method:"POST",raw:true,headers:{"content-type":"video/mp4","x-studio-file-name":encodeURIComponent(file.name)}});state.currentVenue=result.venue;state.venueDirty=false;renderVenueEditor();showToast("Custom venue video added.")}catch(error){showError(error.message)}finally{els.venueVideo.value=""}}
async function removeVenueVideo(){if(!state.currentVenue||!confirm("Remove this venue’s custom video?"))return;try{const result=await api(`/api/studio/venues/${state.currentVenue.id}/video`,null,{method:"DELETE"});state.currentVenue=result.venue;renderVenueEditor();showToast("Custom video removed. The public edition will show the safe placeholder.")}catch(error){showError(error.message)}}

async function generateQrArtwork(){
  if(!state.currentVenue||!state.currentQr?.destination)return;try{els.generateQr.disabled=true;els.qrValidation.textContent="Generating and checking QR…";const image=await loadImage("/assets/jookbox-venue-qr-master-v1.png");const canvas=els.qrCanvas,ctx=canvas.getContext("2d");ctx.clearRect(0,0,1920,1080);ctx.drawImage(image,0,0,1920,1080);els.qrSource.replaceChildren();new QRCode(els.qrSource,{text:state.currentQr.destination,width:384,height:384,colorDark:"#020914",colorLight:"#ffffff",correctLevel:QRCode.CorrectLevel.H});await nextFrame();const source=els.qrSource.querySelector("canvas,img,svg");if(!source)throw new Error("QR engine did not produce an image.");ctx.fillStyle="#fff";ctx.fillRect(919,376,450,450);ctx.drawImage(source,952,409,384,384);drawVenueName(ctx,state.currentVenue.csv.venueName);const validation=await validateQr(canvas,state.currentQr.destination);state.qrReady=true;els.downloadQr.disabled=false;els.printQr.disabled=false;els.qrValidation.textContent=validation.message;els.qrValidation.className=validation.ok?"ok":"warning";els.qrState.textContent=state.currentQr.publiclyDistributable?"Public HTTPS destination embedded.":"Preview only: intended destination is not yet confirmed reachable for public distribution."}catch(error){showError(error.message);els.qrValidation.textContent="QR artwork could not be generated."}finally{els.generateQr.disabled=!state.currentQr?.destination}}
function drawVenueName(ctx,name){ctx.fillStyle="#07152d";ctx.fillRect(835,903,649,99);ctx.strokeStyle="#1576ff";ctx.lineWidth=3;ctx.strokeRect(835,903,649,99);ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillStyle="#f6f8fb";ctx.font='900 64px Impact, "Arial Black", sans-serif';let size=64;while(ctx.measureText(name.toUpperCase()).width>590&&size>28){size-=2;ctx.font=`900 ${size}px Impact, "Arial Black", sans-serif`}ctx.fillText(name.toUpperCase(),1160,953)}
async function validateQr(canvas,expected){if("BarcodeDetector"in window){try{const detector=new BarcodeDetector({formats:["qr_code"]});const codes=await detector.detect(canvas);const match=codes.some(code=>code.rawValue===expected);return{ok:match,message:match?"Scan validation passed: QR decodes to the exact configured destination.":"Automatic scan validation could not confirm the destination. Do not distribute until manually scan-tested."}}catch{}}const title=els.qrSource.title||els.qrSource.querySelector("canvas")?.parentElement?.title||"";return{ok:title===expected,message:title===expected?"QR payload verified structurally. This device does not expose automatic camera-style scan validation; scan the downloaded poster before public distribution.":"QR payload could not be verified."}}
function downloadQrArtwork(){if(!state.qrReady)return;els.qrCanvas.toBlob(blob=>{if(!blob)return;const link=document.createElement("a");link.href=URL.createObjectURL(blob);link.download=`${state.currentVenue.masterId}-${slug(state.currentVenue.csv.venueName)}-jookbox-qr.png`;link.click();setTimeout(()=>URL.revokeObjectURL(link.href),5000)},"image/png")}
function drawQrPlaceholder(){const ctx=els.qrCanvas.getContext("2d");ctx.clearRect(0,0,1920,1080);ctx.fillStyle="#061424";ctx.fillRect(0,0,1920,1080);ctx.fillStyle="#8aa2b8";ctx.textAlign="center";ctx.font="700 42px Arial";ctx.fillText(state.currentQr?.destination?"PRESS GENERATE QR ARTWORK":"PUBLIC OR INTENDED HTTPS DESTINATION REQUIRED",960,540)}

async function api(url,body,{method="POST",token=true,raw=false,headers={}}={}){const options={method,headers:{...headers}};if(token)options.headers["x-deep-cuts-studio-token"]=state.token;if(body!==null&&body!==undefined){if(raw)options.body=body;else{options.headers["content-type"]="application/json";options.body=JSON.stringify(body)}}const response=await fetch(url,options);const result=await response.json().catch(()=>({}));if(!response.ok||result.ok===false)throw new Error(result.error||`Studio request failed (${response.status}).`);return result}
function showToast(message){clearTimeout(state.toastTimer);els.toast.textContent=message;els.toast.classList.add("show");state.toastTimer=setTimeout(()=>els.toast.classList.remove("show"),3800)}
function showError(message){showToast(`Could not complete that: ${message}`)}
function humanStatus(value){return String(value||"never checked").replaceAll("_"," ")}
function sourceLabel(value){return{manual_override:"manual override",automatic_events:"current gig information",csv_facts:"verified CSV facts"}[value]||value}
function formatDateTime(value){if(!value)return"Never";return new Intl.DateTimeFormat("en-AU",{dateStyle:"medium",timeStyle:"short",timeZone:"Australia/Melbourne"}).format(new Date(value))}
function formatBytes(value){const bytes=Number(value||0);if(bytes<1024*1024)return`${Math.round(bytes/1024)} KB`;return`${(bytes/1024/1024).toFixed(1)} MB`}
function displayUrl(value){try{const url=new URL(value);return`${url.hostname}${url.pathname==="/"?"":url.pathname}`.slice(0,64)}catch{return value}}
function escapeHtml(value){return String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]))}
function loadImage(src){return new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=()=>reject(new Error("The supplied JookBox QR master artwork could not be loaded."));image.src=src})}
function nextFrame(){return new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)))}
function slug(value){return String(value||"venue").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,80)||"venue"}
function populateSelect(select,label,values){const active=select.value;select.replaceChildren(new Option(label,""),...values.map(value=>new Option(value,value)));select.value=values.includes(active)?active:""}
