export const validationCommands = [
  test("Platform contracts", "scripts/validate-platform.mjs", 875),
  test("Edition isolation", "scripts/test-edition-isolation.mjs", 110),
  test("Global footer", "scripts/test-global-footer.mjs"),
  test("Discovery experience", "scripts/test-discovery.mjs"),
  test("School challenge", "scripts/test-school-challenge.mjs"),
  test("Laneway artist edition", "scripts/test-laneway-edition.mjs"),
  test("Laneway company edition", "scripts/test-laneway-company-oneoff.mjs"),
  test("Final Indie Label model", "scripts/test-indie-label-model.mjs"),
  test("Laneway reporting", "scripts/test-laneway-reporting.mjs", 120),
  test("Indie Wheel edition", "scripts/test-indie-wheel-edition.mjs"),
  test("Nastyboy Indie Wheel", "scripts/test-nastyboy-indie-wheel.mjs"),
  test("High Grade Mechanical", "scripts/test-high-grade-mechanical.mjs"),
  test("Hays", "scripts/test-hays.mjs"),
  test("External-link policy", "scripts/test-external-links.mjs"),
  test("JookBox", "scripts/test-jookbox.mjs"),
  test("Band JookBox batch", "scripts/test-jookbox-band-batch.mjs"),
  test("Bar Edition JookBox", "scripts/test-bar-jukebox.mjs"),
  test("Canonical Mahogany Jukebox v1 lock", "scripts/test-canonical-mahogany-jukebox-lock.mjs", 180),
  test("Aggits four-button Jukebox", "scripts/test-aggits-jukebox.mjs"),
  test("Aggits Jukebox bulk importer", "scripts/test-aggits-jukebox-import.mjs", 180),
  test("Aggits Jukebox protected publisher", "scripts/test-aggits-jukebox-publisher.mjs", 240),
  test("Shared JookBox coin audio", "scripts/test-jookbox-coin-audio.mjs", 60),
  test("Direct Bar publisher", "scripts/test-bar-publisher.mjs", 240),
  test("Record Company", "scripts/test-record-company.mjs", 950),
  test("Analytics", "scripts/test-analytics.mjs"),
  test("Build tracking", "scripts/test-build-tracking.mjs", 135),
  test("Worker contracts", "scripts/test-worker.mjs"),
  test("Sales intelligence", "scripts/test-sales-intelligence.mjs"),
  test("Edition synchronisation", "scripts/test-sync-editions.mjs", 315),
  test("Runtime secrets", "scripts/test-runtime-secrets.mjs"),
  test("Live delivery", "scripts/test-live-delivery.mjs"),
  test("One-prompt factory", "scripts/test-factory.mjs", 270),
  test("Batch controller", "scripts/test-batch.mjs"),
  test("Studio JookBox research", "scripts/test-studio-jookbox-research.mjs"),
  test("Studio Venue Library", "scripts/test-venue-library.mjs", 220),
  test("Venue batch publication", "scripts/test-venue-batch-publication.mjs", 300),
  test("Deep Cuts Studio", "scripts/test-studio.mjs", 205),
  test("Performance pipeline", "scripts/test-performance-pipeline.mjs"),
  check("Batch entry point", "scripts/deep-cuts-batch.mjs"),
  check("Delivery artwork builder", "scripts/build-delivery-assets.mjs"),
  check("Bounded parallel helper", "scripts/lib/parallel.mjs"),
  check("Record Company start", "scripts/record-company/start.mjs"),
  check("Record Company completion", "scripts/record-company/send-completion.mjs"),
  check("Laneway roster resolver", "scripts/resolve-laneway-company-roster.mjs"),
  check("Laneway video audit", "scripts/audit-laneway-company-videos.mjs"),
  check("Studio JookBox research implementation", "scripts/studio-jookbox-research.mjs"),
  check("Studio server", "scripts/studio-server.mjs"),
  check("Secure Bar Edition publisher", "scripts/bar-edition-publication.mjs"),
  check("Venue batch publisher", "scripts/venue-batch-publication.mjs"),
  check("Venue QR artwork", "scripts/venue-qr-artwork.mjs"),
  check("Cloudflare Bar publisher", "worker/bar-publisher.js"),
  check("Cloudflare Aggits Jukebox publisher", "worker/aggits-jukebox-publisher.js"),
  check("Aggits Jukebox QR artwork", "scripts/aggits-jukebox-qr-artwork.mjs"),
  check("Band JookBox batch controller", "scripts/jookbox-band-batch.mjs"),
  check("Band JookBox batch mapping", "scripts/jookbox-band-batch-lib.mjs"),
  check("Band JookBox batch reconciliation", "scripts/reconcile-jookbox-band-batch.mjs"),
  check("Character JookBox QR renderer", "scripts/render-character-jookbox-qr.mjs"),
  check("Studio model", "scripts/studio-model.mjs"),
  check("Aggits Jukebox preview", "scripts/aggits-jukebox-preview.mjs"),
  check("Aggits Jukebox icon library", "scripts/aggits-jukebox-icons.mjs"),
  check("Aggits Jukebox bulk importer", "scripts/aggits-jukebox-import.mjs"),
  check("Studio import interface", "studio/import-editions.js"),
  check("Studio interface", "studio/app.js"),
  check("Studio desktop shell", "studio/desktop-main.mjs"),
  check("Desktop packaging", "forge.config.cjs"),
  check("Discovery application", "js/app.js"),
  check("School quiz", "js/school-quiz.js"),
  check("Laneway quiz", "js/laneway-quiz.js"),
  check("Laneway company quiz", "js/laneway-company-quiz.js"),
  check("Business quiz", "js/business-quiz.js"),
  check("Analytics client", "js/analytics.js"),
  check("Interaction helpers", "js/interactions.js"),
  check("Reporting client", "js/reporting.js"),
  check("Report interface", "js/report.js"),
  check("Sales interface", "sell/app.js"),
  check("Sales schemas", "sell/schemas.js"),
  check("Sales demo data", "sell/demo-data.js"),
  check("Record Company interface", "record-company/app.js"),
  check("Record Company schemas", "record-company/schemas.js"),
  check("Record Company Worker", "worker/record-company.js"),
  check("Sales Worker", "worker/sales.js"),
  check("Laneway report Worker", "worker/laneway-report.js"),
  check("Primary Worker", "worker/index.js")
];

function test(label, file, estimatedMs = 60) {
  return { label, args: [file], estimatedMs };
}

function check(label, file) {
  return { label, args: ["--check", file], estimatedMs: 40 };
}
