const ACCESSED="2026-07-23T00:00:00.000Z";

const sources=[
  source("strategy","Our corporate strategy","Telstra",null,"https://www.telstra.com.au/aboutus/our-company/our-corporate-strategy","official_company","Connected Future 30 priorities and operating model"),
  source("annual25","Annual Report 2025","Telstra","2025-08-25","https://www.telstra.com.au/aboutus/investors/reports","annual_report","Latest published annual report and current performance context"),
  source("investor25","2025 Telstra Investor Day","Telstra","2025-05-27","https://www.telstra.com.au/aboutus/investors/investor-presentations","investor_presentation","Management priorities, investment and execution plans"),
  source("supplier-code","Telstra Group Supplier Code of Conduct","Telstra","2024-01-01","https://www.telstra.com.au/content/dam/tcom/about-us/our-company/pdf/telstra-supplier-code-of-conduct.pdf","supplier_policy","Minimum supplier standards"),
  source("supplier-governance","Telstra Supplier Governance Statement","Telstra","2025-01-01","https://www.telstra.com.au/content/dam/tcom/about-us/our-company/pdf/supplier-governance-statement.pdf","supplier_policy","Risk assessment, due diligence and contracting process"),
  source("supplier-page","Working with Telstra","Telstra",null,"https://www.telstra.com.au/aboutus/our-company/supplying-to-telstra/working-with-telstra","procurement","Public supplier and payment information"),
  source("leadership","Leadership team","Telstra",null,"https://www.telstra.com.au/aboutus/our-company/leadership-team","official_company","Current senior leadership and responsibilities"),
  source("tio25","Annual Report 2024–25","Telecommunications Industry Ombudsman","2025-10-15","https://www.tio.com.au/reports/annual-report-2024-25","regulator_independent","Sector complaint themes and Telstra complaint movement"),
  source("acma25","Telco complaints data reveals varied consumer issues","Australian Communications and Media Authority","2025-12-19","https://www.acma.gov.au/articles/2025-12/telco-complaints-data-reveals-varied-consumer-issues","regulator","Current complaint handling comparison")
];

export const TELSTRA_IDENTITY={
  id:"au-asx-tls",officialName:"Telstra Group Limited",tradingName:"Telstra",website:"https://www.telstra.com.au",
  industry:"Telecommunications and digital infrastructure",location:"Australia",publicStatus:"ASX-listed (TLS)",registration:"ABN 56 650 620 303",
  matchConfidence:"high",identityEvidence:["annual25","leadership"]
};

export function telstraMatches(query,website=""){
  const normalized=String(query||"").toLowerCase().replace(/[^a-z0-9]/g,"");
  let host="";try{host=new URL(website).hostname.replace(/^www\./,"").toLowerCase()}catch{}
  return ["telstra","telstragroup","telstragrouplimited"].includes(normalized)||host==="telstra.com.au"?[TELSTRA_IDENTITY]:[];
}

export function buildTelstraReport(offering={}){
  const offer=String(offering.description||"").trim();
  const sellerName=String(offering.businessName||"").trim();
  const sellerWebsite=String(offering.website||"").trim();
  const offerLabel=offer||(sellerWebsite?`the publicly presented capabilities of ${sellerName||sellerWebsite}`:"your product or service");
  const fit=fitFor(offer,sellerWebsite);
  const sections={
    priorities:section("What they are trying to achieve",[
      insight("Become the first choice for connectivity","confirmed_fact","Telstra describes Connected Future 30 as its plan to become Australia’s number-one choice for connectivity.","Customer experience, network performance and dependable delivery are central—not side issues.",`Show how ${offerLabel} can improve reliability, customer outcomes or the speed of delivery.`,"Tie your opening to one measurable operational outcome rather than a broad claim.","Which Connected Future 30 outcome is creating the most pressure for your team right now?","High confidence",["strategy","annual25"]),
      insight("Reinvent the network and digital infrastructure","confirmed_fact","The strategy highlights network leadership, capturing more value from the network and leading digital infrastructure.","Large technology and infrastructure programs usually increase scrutiny of implementation risk, resilience and supplier capability.","If relevant, lead with evidence that you can operate safely at scale and integrate without disrupting critical services.","Bring one comparable delivery example with scope, timing and measured result.","Where are external suppliers most useful in delivering the infrastructure program?","High confidence",["strategy","investor25"]),
      insight("Keep simplifying while investing","strong_interpretation","Current strategy and investor material put investment, value creation and disciplined execution side by side.","Teams may be asked to improve outcomes without adding avoidable complexity or cost.","A proposal that reduces manual work or consolidates vendors may travel better than a feature-heavy proposal.","Quantify time, cost and operational effort—not just product capability.","What work is the team trying to simplify or remove over the next year?","Moderate confidence",["strategy","investor25"])
    ]),
    values:section("What they appear to value",[
      insight("Reliability and resilience","strong_interpretation","Telstra’s core strategy depends on leading connectivity and digital infrastructure.","A failure can affect essential services and customer trust, so delivery risk is likely to matter heavily.","Lead with service levels, continuity plans, incident response and evidence of consistent delivery.","Put proof of reliability before generic innovation language.","What evidence do you require before trusting a new supplier in a critical environment?","High confidence",["strategy","supplier-governance"]),
      insight("Responsible, secure supply chains","confirmed_fact","The Supplier Code covers labour and human rights, safety, environment, integrity, cyber security, privacy and supplier diversity.","A good sales pitch will not compensate for weak governance documentation.","Prepare policies, certifications and supply-chain evidence before procurement asks for them.","Run a readiness check against the Supplier Code before approaching Telstra.","Which supplier-risk categories are most material for this engagement?","High confidence",["supplier-code","supplier-governance"]),
      insight("Evidence over promises","strong_interpretation","Supplier governance includes risk assessment, Know Your Supplier due diligence, external screening and evidence of accreditations.","Claims are likely to be tested during onboarding.","Use verifiable proof, named references and clear performance measures.","Create a one-page evidence pack with links to supporting documents.","What evidence most often delays a new supplier’s approval?","High confidence",["supplier-governance"])
    ]),
    pressures:section("Their likely business pressures",[
      insight("Deliver investment while controlling complexity","strong_interpretation","Telstra is pursuing a large strategy across network, customer experience and digital infrastructure.","Several programs running together may put pressure on delivery capacity and governance.","Position extra capability as controlled capacity, not another layer to manage.","Explain ownership, reporting and escalation in plain terms.","Where does delivery capacity become tight across the current program?","Moderate confidence",["strategy","investor25"]),
      insight("Customer service and complaint resolution remain visible","confirmed_fact","The TIO reported Telstra complaints fell 3.2% in 2024–25, while ACMA later reported an eight-day average complaint resolution time and 9.3% referral to the TIO for the measured quarter.","Improvement and continuing pressure can both be true. Service reliability and resolution speed remain externally visible.","If your offer affects service or operations, connect it to fewer hand-offs, faster resolution or clearer customer communication.","Avoid saying their service is broken; use the regulator data as a careful question.","Which part of the service journey creates the longest delay today?","High confidence",["tio25","acma25"],"Sector-wide conditions and company scale also affect complaint volumes."),
      insight("Supplier risk is actively governed","confirmed_fact","Telstra assesses suppliers across operational, commercial, resilience, privacy, information security, safety, integrity and other risk categories.","A new supplier can create work for several gatekeepers before it creates value.","Reduce perceived onboarding risk with complete documentation and a contained first engagement.","Offer a pilot with defined controls and exit criteria.","Which supplier-risk assessment should we prepare for first?","High confidence",["supplier-governance"])
    ]),
    opportunities:section("Where you may be able to help",[
      insight(fit.title,fit.status,fit.found,fit.meaning,fit.relevance,fit.action,fit.question,fit.confidence,fit.sources),
      insight("Reduce the effort of managing a new supplier","possible_interpretation","Telstra’s published due-diligence process is extensive.","A proposal that is simple to evaluate and govern may face less friction.","Make scope, ownership, controls, reporting and pricing easy to inspect.","Propose one contained use case with a clear success measure.","Would a limited pilot make this easier to assess without creating unnecessary risk?","Moderate confidence",["supplier-governance"])
    ]),
    buying:section("How they buy",[
      insight("Expect formal qualification before substantial work","confirmed_fact","Telstra says most supplier engagements use risk assessment, Know Your Supplier due diligence, external screening and standard contracting.","A cold pitch alone is unlikely to complete the buying process.","Treat the first conversation as earning the next step, then prepare for formal checks.","Have corporate, insurance, security, safety and compliance material ready.","What registration or prequalification step applies to this category?","High confidence",["supplier-governance"]),
      insight("The exact entry route is not fully public","unknown","Public material explains governance but does not provide one universal open tender portal for every category.","The route may vary by business unit, category and controlled entity.","Confirm the relevant procurement path before investing in a long proposal.","Use Telstra’s official supplier information and an appropriate business function; do not guess a buyer’s private details.","Who owns this category, and what is the correct supplier-entry process?","Low confidence",["supplier-page"])
    ]),
    supplierExpectations:section("What they expect from suppliers",[
      insight("A broad compliance baseline","confirmed_fact","The Supplier Code sets minimum standards for rights, safety, environment, integrity, cyber security, privacy and supplier diversity.","Your whole operating model may be considered, not only the service being sold.","Map each applicable requirement to evidence and an accountable person in your business.","Prepare a compliance index instead of sending a folder of unexplained documents.","Which parts of the Supplier Code are most important for this scope?","High confidence",["supplier-code"]),
      insight("Ongoing evidence and monitoring","confirmed_fact","Supplier governance includes screening, due diligence and ongoing performance monitoring.","Approval is not the end of supplier scrutiny.","Show how you will report performance and keep records current.","Include service reporting and review cadence in the proposal.","How will supplier performance be measured after appointment?","High confidence",["supplier-governance"])
    ]),
    projects:section("Current priorities and projects",[
      insight("ACTIVE — Connected Future 30","confirmed_fact","Telstra’s current corporate strategy is Connected Future 30, focused on customer connectivity, the network and digital infrastructure.","Projects that support these outcomes have a clearer strategic link than generic improvement claims.","Name the specific outcome your offer supports and how it will be measured.","Reference the current strategy date and official wording accurately.","Which program within Connected Future 30 is most open to external capability?","High confidence",["strategy","investor25"]),
      insight("Current project-level demand is not proven","unknown","Public strategy material does not prove that Telstra is currently buying the user’s specific offering.","Strategic relevance is not the same as a live opportunity.","Use discovery questions before treating this as qualified demand.","Ask about timing, budget, incumbent arrangements and the next procurement window.","Is there an active initiative and approved budget for this problem?","High confidence",["strategy"])
    ]),
    executives:{title:"Key executives and management",items:[
      insight("Leadership is verified from the official current team page","confirmed_fact","Telstra publishes its current leadership team and responsibilities.","Senior names are useful for context, but the most senior person is rarely the best first contact.","Choose the function closest to the problem and respect procurement channels.","Use official profiles only; never guess emails or private phone numbers.","Which leader owns the operational result this proposal affects?","High confidence",["leadership"])
    ],people:[
      {name:"Vicki Brady",title:"Chief Executive Officer and Managing Director",area:"Enterprise leadership",why:"Sets the Connected Future 30 direction. Relevant for strategic context, not normally a first sales contact.",approach:"Official company channels and public industry events only.",sourceId:"leadership",verifiedAt:ACCESSED,confidence:"High confidence"},
      {name:"Michael Ackland",title:"Chief Financial Officer and Group Executive, Strategy & Finance",area:"Strategy, finance and procurement",why:"The official profile states that his function includes procurement, making the portfolio relevant to commercial governance.",approach:"Use the proper procurement or relevant business-unit route rather than approaching the CFO directly.",sourceId:"leadership",verifiedAt:ACCESSED,confidence:"High confidence"}
    ]},
    teams:section("Relevant teams and decision-makers",[
      insight("The operating team is likely to be the user and evaluator","strong_interpretation","The function that owns the problem will need to validate practical fit and implementation.","Procurement cannot create operational sponsorship for you.","Find the team responsible for the outcome before presenting a commercial package.","Lead with their workflow, risk and outcome—not your product catalogue.","Who owns the result and who would use this day to day?","Moderate confidence",["strategy"]),
      insight("Procurement and supplier governance are commercial gatekeepers","confirmed_fact","Procurement sits within Strategy & Finance, and the published governance process includes due diligence and contracting.","They may evaluate risk, terms, evidence and process even when another team wants the solution.","Prepare transparent scope, price structure, references and compliance evidence.","Ask the sponsor to introduce the correct procurement path.","What must be complete before procurement can assess us?","High confidence",["leadership","supplier-governance"]),
      insight("Security, privacy and risk may be evaluators","confirmed_fact","Cyber security, privacy, resilience and other risks are named supplier-assessment categories.","These teams may stop or reshape an engagement.","Surface data handling, access, resilience and incident controls early.","Bring a short control summary and answer gaps honestly.","Which security and privacy reviews apply to this scope?","High confidence",["supplier-code","supplier-governance"])
    ]),
    feedback:section("Customer and market feedback",[
      insight("Complaints improved, but resolution remains a pressure point","confirmed_fact","The TIO reported fewer Telstra complaints year on year, while ACMA’s later quarterly comparison showed longer resolution than some large competitors.","There is evidence of improvement and evidence that resolution experience can still matter.","If your offer touches service, frame it around measurable reduction in delay or repeat contact.","Use the data carefully and ask rather than diagnose.","Which recurring customer issue is hardest to resolve at first contact?","High confidence",["tio25","acma25"],"The sources measure different periods and metrics, so they should not be collapsed into one score."),
      insight("Public feedback cannot reveal internal root causes","unknown","External complaint data shows outcomes, not the internal cause of each complaint.","Assuming a cause could undermine credibility.","Validate the operational cause with the relevant team.","Ask where delays originate before proposing a solution.","What sits behind the measured resolution time in your area?","High confidence",["acma25"])
    ]),
    risks:section("Risks before approaching them",[
      insight("A long, controlled sales cycle is plausible","strong_interpretation","Published supplier governance includes several risk and due-diligence steps.","Time to contract may be longer than the initial interest suggests.","Qualify process, sponsor, timing and documentation early.","Budget for a staged pursuit and agree the next decision point.","What are the approval stages and realistic timing for this category?","High confidence",["supplier-governance"]),
      insight("Strategic fit may be mistaken for active demand","possible_interpretation","Public priorities show direction but not a live buying decision for this offer.","A polished proposal may still be premature.","Confirm problem, owner, urgency and budget before customising heavily.","Use a short discovery document before a full proposal.","Is this a current funded priority or a future possibility?","High confidence",["strategy"]),
      insight("Incumbent supplier position is unknown","unknown","No reliable public source reviewed identifies the incumbent for this specific offering.","Replacement risk and switching cost cannot yet be assessed.","Ask about the existing model without assuming dissatisfaction.","Offer a complementary pilot if replacement is unrealistic.","What works well in the current arrangement, and where are the gaps?","Low confidence",["supplier-page"])
    ]),
    approach:section("How I would approach them",approachInsights(offerLabel)),
    questions:section("Questions to ask",questionInsights()),
    firstMeeting:section("What to say in the first meeting",meetingInsights(offerLabel)),
    notToDo:section("What not to do",[
      insight("Do not bypass formal procurement","confirmed_fact","Telstra publishes formal supplier due-diligence and governance requirements.","Trying to route around them can create risk for your internal sponsor.","Ask for the correct process and prepare for it.","Keep outreach professional and role-relevant.","What is the proper path for a new supplier in this category?","High confidence",["supplier-governance"]),
      insight("Do not claim an internal problem from public data","strong_interpretation","Regulator and strategy sources show outcomes and priorities, not private operating causes.","Overclaiming can make accurate research look intrusive or careless.","Frame evidence as context and ask for validation.","Use ‘we noticed’ and ‘may’ rather than ‘we know’.","Does that public picture match what your team is seeing?","High confidence",["tio25","strategy"]),
      insight("Do not lead with a generic company story","possible_interpretation","A large organisation is likely to receive many broad supplier approaches.","Generic background consumes limited meeting time without proving relevance.","Use one sentence about your business, then move to their outcome and questions.","Bring supporting detail but do not present it unless relevant.","Would it help if I briefly explain the one result most relevant to this issue?","Moderate confidence",["supplier-governance"])
    ]),
    tomorrow:section("If I were meeting them tomorrow",tomorrowInsights(offerLabel)),
    evidence:{title:"Evidence and sources",items:[
      insight("Evidence register","confirmed_fact",`${sources.length} public sources support this demonstration briefing. Official company and regulatory material is prioritised.`,"Every important conclusion can be traced to a dated source; interpretations remain labelled.","Open the source before using a finding in a real conversation.","Refresh the briefing when decisions depend on current people, projects or procurement rules.","What has changed since this research cut-off?","High confidence",sources.map(item=>item.id))
    ]}
  };
  return {schemaVersion:"1.0",reportVersion:"commercial-instinct-demo-1",objective:"sell_to_company",business:TELSTRA_IDENTITY,offering,researchMode:"verified_demo",researchedAt:ACCESSED,researchCutoff:"2026-07-23T00:00:00.000Z",notice:"Commercial Instinct uses public evidence and clearly labelled interpretation. It cannot prove an internal need, buying decision or final decision-maker.",unknowns:["Current budget and buying timetable","Incumbent supplier arrangements","The final decision group for this offering","Whether an active requirement exists"],sources,sections,stagesCompleted:["Confirming the target company","Reviewing official target-company information","Checking current priorities and pressures","Checking procurement and supplier expectations","Reviewing relevant leadership and market evidence","Comparing the two companies","Preparing candid sales advice"]};
}

function source(id,title,publisher,publishedAt,url,type,relevance){return {id,title,publisher,publishedAt,url,sourceType:type,relevance,accessedAt:ACCESSED,insightIds:[]}}
function section(title,items){return {title,items}}
function insight(title,status,found,meaning,relevance,action,question,confidence,sourceIds,alternativeExplanation=""){return {id:title.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,""),title,status,found,meaning,relevance,action,question,confidence,sourceIds,alternativeExplanation}}

function fitFor(offer,website=""){
  const text=offer.toLowerCase();
  if(/cyber|security|privacy|software|technology|automation|data/.test(text))return {title:"A controlled technology use case may be relevant",status:"possible_interpretation",found:"Telstra names technology leadership and digital infrastructure as priorities, while supplier governance explicitly assesses cyber security, privacy and resilience.",meaning:"A technology offer may align, but it will face strong control and integration questions.",relevance:"Strong possible fit if the offer produces a measurable outcome and can satisfy enterprise controls.",action:"Lead with a contained use case, architecture boundaries, security evidence and measurable value.",question:"Which controlled use case would be useful without creating unnecessary integration risk?",confidence:"Moderate confidence",sources:["strategy","supplier-governance"]};
  if(/clean|facility|maintenance|property|safety|energy/.test(text))return {title:"Operational reliability may create a practical fit",status:"possible_interpretation",found:"Telstra operates national infrastructure and assesses suppliers for operational, resilience, safety and environmental risk.",meaning:"A facilities or operational offer may matter where it improves consistency across sites, but no live requirement is public.",relevance:"Moderate possible fit if geographic coverage and governance can be proven.",action:"Lead with coverage, response times, safety performance and central reporting.",question:"Where do current site-service arrangements create inconsistent outcomes?",confidence:"Moderate confidence",sources:["strategy","supplier-governance"]};
  return {title:"The commercial fit still needs to be qualified",status:"possible_interpretation",found:offer?`The user described the offer as “${offer}”. Public material shows broad priorities but no verified current requirement for this specific offer.`:website?`A supplier website was provided, but this credential-free demonstration does not claim to have researched or interpreted that website.`:"No supplier offering was provided.",meaning:"A plausible strategic connection is not evidence of active demand.",relevance:offer?"Weak or unproven fit until an operating problem, owner and timing are confirmed.":website?"The target-company briefing is useful, but supplier-specific fit remains unproven until the live research provider reviews both sites.":"Insufficient information for a tailored fit assessment.",action:"Use a short discovery conversation before preparing a detailed proposal.",question:"Is there a current problem in this area, and what outcome would justify change?",confidence:"Low confidence",sources:["strategy","supplier-page"]};
}

function questionInsights(){return [
  insight("Understanding their priorities","possible_interpretation","Public material sets broad company priorities, but the team-level priority is unknown.","The meeting must connect corporate direction to the person’s real work.","Ask which Connected Future 30 outcome is creating the most pressure this year.","Listen for a measurable problem, owner and deadline.","Which outcome is most important to your team this year?","Moderate confidence",["strategy"]),
  insight("Understanding current problems","unknown","Public evidence cannot confirm the team’s internal operating problem.","Diagnosing before listening risks solving the wrong issue.","Ask where time, cost, risk or customer frustration is currently greatest.","Separate symptoms from the underlying cause.","Where does the current process create the most friction?","High confidence",["strategy"]),
  insight("Understanding existing suppliers","unknown","The current arrangement for this offering is not public.","You cannot responsibly assume dissatisfaction or replacement intent.","Ask what works well and where the existing arrangement creates friction.","Explore complementing the incumbent before proposing replacement.","What would need to be true for you to consider a new supplier?","High confidence",["supplier-page"]),
  insight("Understanding procurement","confirmed_fact","Formal supplier risk and due-diligence processes apply.","Process and evidence can decide whether interest progresses.","Ask which qualification, security, safety or commercial reviews apply.","Agree the next process step and its owner.","What normally prevents a new supplier from progressing?","High confidence",["supplier-governance"]),
  insight("Understanding timing","unknown","No current buying timetable for this offer is public.","A real problem may still be too early or too late for a proposal.","Ask about decision dates, contract windows and dependencies.","Match follow-up effort to a real timetable.","When would a decision need to be made for this to have value?","High confidence",["supplier-page"]),
  insight("Understanding decision criteria","strong_interpretation","Reliability, evidence and supplier controls are prominent in official material.","The final criteria may extend beyond price and product features.","Ask how options will be judged and weighted.","Mirror confirmed criteria in any later proposal.","What are the three most important criteria when you compare suppliers?","High confidence",["supplier-code","supplier-governance"]),
  insight("Understanding risk","confirmed_fact","Supplier assessment can cover operational, commercial, resilience, privacy, security and safety risks.","An unaddressed control can stop a commercially attractive idea.","Ask which risks will receive the most scrutiny.","Offer evidence early and disclose gaps honestly.","What would make this feel too risky to progress?","High confidence",["supplier-governance"]),
  insight("Understanding success measures","unknown","Public strategy provides direction but not the team’s success measures for this offer.","Without a measure, value and accountability remain vague.","Ask for baseline, target, timeframe and owner.","Use their measure in a contained pilot proposal.","What would a successful outcome look like twelve months from now?","High confidence",["strategy"])
]}

function approachInsights(offer){return [
  insight("Your likely opening angle","strong_interpretation",`The strongest public signals are disciplined execution, reliability and supplier risk control. The supplied offer is: ${offer}.`,"A narrow outcome is easier for an operational sponsor and procurement team to evaluate.",`Connect ${offer} to one current outcome, prove delivery and make governance easy.`,"Open with one observed priority and ask whether it is relevant to their team.","Which current outcome is hardest for your team to deliver?","High confidence",["strategy","supplier-governance"]),
  insight("Why they may care now","possible_interpretation","Connected Future 30 combines network, customer and digital-infrastructure ambitions with disciplined delivery.","Teams delivering change may value capacity that reduces risk or effort.","Connect urgency to a dated current program, not a generic trend.","Ask whether the program creates a live requirement before claiming demand.","Is this issue affecting a current program or delivery date?","Moderate confidence",["strategy","investor25"]),
  insight("Benefits to emphasise","strong_interpretation","Reliability, resilience, measurable outcomes and controlled supplier risk recur in the evidence.","These benefits may carry more weight than a long feature list.","Prioritise lower risk, consistent service, clear reporting, easier implementation and measurable time or cost impact where true.","Support each benefit with a result or control.","Which outcome would carry the most value internally?","High confidence",["strategy","supplier-governance"]),
  insight("What not to lead with","possible_interpretation","No public evidence shows lowest initial price is the only or primary criterion for this scope.","A price-only opening can make a controlled service look interchangeable.","Do not lead with generic innovation, company history or an unsupported saving.","Start with their outcome, then evidence, then commercial detail.","Is cost reduction the main objective, or is another outcome more important?","Moderate confidence",["supplier-code","supplier-governance"]),
  insight("Evidence to reference","confirmed_fact","Connected Future 30, current investor material and supplier-governance documents are public and current enough for careful reference.","Using the company’s actual published language shows preparation.","Mention one relevant statement and its date; do not recite the research.","Keep the original source open in case the wording is challenged.","Does that published priority reflect what your team is focused on?","High confidence",["strategy","investor25","supplier-governance"]),
  insight("Proof they may expect","strong_interpretation","Due diligence requires evidence of systems, accreditations and controls.","Claims will need to survive operational and commercial review.","Prepare relevant case studies, references, service performance, certifications, insurance and an implementation plan.","Put proof in a concise indexed pack.","Which proof points are mandatory before technical or commercial review?","High confidence",["supplier-governance"]),
  insight("Likely objections","possible_interpretation","A new supplier adds onboarding, integration, risk and management effort.","Even a useful offer may lose to the safety of the current arrangement.","Expect questions about incumbents, scale, security, disruption, references and total cost.","Answer with evidence and acknowledge what is not yet known.","What would stop this from being worth the change effort?","Moderate confidence",["supplier-governance"]),
  insight("How to reduce their risk","strong_interpretation","A contained first step can limit exposure while producing evidence.","Lowering decision risk may be more persuasive than increasing promises.","Offer a pilot or staged scope with measures, controls, review points and exit conditions.","Define ownership, reporting and incident escalation before starting.","Would a contained pilot make this easier to assess?","High confidence",["supplier-governance"]),
  insight("Who to approach","strong_interpretation","The operating team is the likely problem owner; procurement and risk functions are likely gatekeepers.","The CEO is strategic context, not the default sales target.","Approach the role closest to the outcome and ask for the proper procurement route.","Use official channels and public professional pathways only.","Who owns this outcome, and who manages the supplier process?","High confidence",["leadership","supplier-governance"]),
  insight("Suggested first contact","possible_interpretation","No universal individual buyer can be verified publicly.","A concise, evidence-aware message is safer than a personalised claim about internal problems.","Say: ‘We noticed your focus on [specific current priority]. We helped [relevant customer type] achieve [measured result]. Is this an issue your team is working on, and who owns it?’","Do not attach a long proposal to the first contact.","Would a short exploratory conversation be useful?","Moderate confidence",["strategy","leadership"])
]}

function tomorrowInsights(offer){return [
  insight("Know these five things","strong_interpretation","Strategy centres on connectivity, network value and digital infrastructure; supplier risk is formal; evidence matters; customer resolution remains visible; and public strategy does not prove live demand.","These points keep the meeting relevant without pretending to know internal conditions.","Use them as a listening framework, not a script.","Put the five points on one preparation card.","Which of these priorities is most relevant to your team today?","High confidence",["strategy","supplier-governance","acma25"]),
  insight("Focus on these three issues","strong_interpretation","The best evidenced themes are reliable execution, measurable improvement and controlled supplier risk.","They connect strategy to practical buying concerns.","Use only the themes your offer can genuinely support.","Prepare one proof point for each relevant theme.","Which of reliability, measurable improvement or lower risk matters most here?","High confidence",["strategy","supplier-governance"]),
  insight("Ask these five questions","possible_interpretation","The critical unknowns are the current problem, desired result, incumbent arrangement, decision criteria and timetable.","Answers determine whether this is a real opportunity.","Ask one natural question on each topic and listen more than you present.","Write the answers in the company’s language.","What problem matters, what result is required, what exists now, how will you decide, and by when?","Moderate confidence",["strategy","supplier-governance"]),
  insight("Bring this evidence","strong_interpretation","Supplier governance signals that claims, accreditations and controls can be tested.","Prepared evidence reduces risk and follow-up delay.","Bring one comparable case study, reference, service data, relevant certifications, insurance summary and a simple implementation option.","Carry detail separately so the meeting stays concise.","Which evidence would you need before considering a next step?","High confidence",["supplier-governance"]),
  insight("Avoid these mistakes","strong_interpretation","The evidence does not prove an internal problem, live requirement or unhappy incumbent.","Overclaiming, bypassing process or pitching the CEO can damage credibility.","Do not diagnose, assume demand, lead only with price or ignore procurement.","Use evidence as a question, not a claim of inside knowledge.","Does the public picture match what your team is seeing?","High confidence",["strategy","supplier-page"]),
  insight("Your best opening","possible_interpretation",`‘I saw Telstra is focused on delivering Connected Future 30 while keeping supplier risk controlled. We provide ${offer}. Rather than assume where it fits, I’d like to understand which outcome is hardest for your team to deliver and whether our evidence is relevant.’`,"It shows preparation while allowing correction.","Keep the opening under 30 seconds, then ask a question.","Practise it once; do not make it sound memorised.","What would make this conversation useful for you?","Moderate confidence",["strategy","supplier-governance"]),
  insight("Your strongest possible angle","possible_interpretation",`Position ${offer} as a contained way to improve a named outcome while reducing implementation and supplier risk.`,"It connects the offer to both operational value and the published buying environment.","Use a real result and a limited first step.","Drop the angle if discovery shows the problem is not current.","Would a controlled first step be useful in this area?","Moderate confidence",["strategy","supplier-governance"]),
  insight("Who may matter","strong_interpretation","The relevant operating owner, procurement, supplier governance and applicable security, privacy or safety evaluators are the likely group.","Each can advance or stop the proposal for a different reason.","Tailor the message to user outcome, commercial process and risk evidence.","Ask the sponsor who else must be involved.","Who will use, evaluate, approve and commercially manage this?","High confidence",["leadership","supplier-governance"]),
  insight("What remains unknown","unknown","A live requirement, budget, timing, incumbent arrangement and final decision group could not be verified publicly.","These are qualification questions, not gaps to fill with assumptions.","Use the first meeting to confirm them.","Do not produce a detailed proposal until the unknowns are reduced.","Is there an active initiative, who owns it, and what is the buying timetable?","High confidence",["supplier-page"])
]}

function meetingInsights(offer){return [
  insight("15-minute meeting","possible_interpretation",`Open with one observed priority and one sentence about ${offer}. Ask two qualification questions. Share one proof point. Close by agreeing whether a second conversation is useful.`,"Short meetings reward focus and curiosity.","Aim to learn the problem, owner and next step—not close a contract.","Prepare a 30-second opening and one comparable result.","Is there enough relevance here to involve the operational owner?","Moderate confidence",["strategy"]),
  insight("30-minute meeting","possible_interpretation","Use five minutes for context, fifteen for their priorities and current arrangement, five for relevant evidence and five to agree the next step.","Discovery should take more time than presenting.","Confirm success measures, risk review and buying route.","Bring a one-page pilot outline only if the need is real.","What evidence would you need to assess a next step?","Moderate confidence",["supplier-governance"]),
  insight("60-minute meeting","possible_interpretation","Add operational users and relevant risk or procurement people. Map the current process, desired outcome, constraints, controls, commercial path and a contained next step.","A longer session can reduce rework if the right functions attend.","End with named owners, evidence requested and a date—not a vague promise to follow up.","Send a concise written recap for confirmation.","Who else needs to validate the problem or proposed first step?","Moderate confidence",["supplier-governance","leadership"])
]}
